services:
  minio:
    image: minio/minio:RELEASE.2024-09-22T00-33-43Z
    command:
      - server
      - "/data"
    environment:
      MINIO_ROOT_USER: Q3AM3UQ867SPQQA43P2F
      MINIO_ROOT_PASSWORD: "zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG"
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 1g

  ready:
    image: andrewlock/wait-for-dependencies
    command: minio:9000
    depends_on:
      - minio
