version: '2'

services:
  minio:
    image: minio/minio
    command:
      - server
      - "/data"
    environment:
      MINIO_ACCESS_KEY: Q3AM3UQ867SPQQA43P2F
      MINIO_SECRET_KEY: "zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG"
    ports:
      - "9000:9000"
