services:
  minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z
    command:
      - server
      - "/data"
    environment:
      MINIO_ROOT_USER: Q3AM3UQ867SPQQA43P2F
      MINIO_ROOT_PASSWORD: "zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG"
    ports:
      - "9000:9000"

  ready:
    image: andrewlock/wait-for-dependencies
    command: minio:9000
    depends_on:
      - minio
